# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-29 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0004_auto_20170529_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotfield',
            name='day',
            field=models.CharField(choices=[('mon', 'Monday'), ('thu', 'Thursday')], default='mon', max_length=3),
            preserve_default=False,
        ),
    ]
