# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-29 11:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0005_slotfield_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to=settings.AUTH_USER_MODEL),
        ),
    ]
