# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-29 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0006_auto_20170529_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='schema.SlotField', unique=True),
        ),
    ]
