# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_operations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='operations',
        ),
    ]
