# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_operations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manageoperation',
            options={'ordering': ['-date_opened', '-date_closed']},
        ),
    ]
