# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-05 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='12345', max_length=255),
            preserve_default=False,
        ),
    ]
