# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160607_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('S', 'Studerende'), ('P', 'Professor')], default='S', max_length=1),
        ),
    ]
