# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160607_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('S', 'Studerende'), ('P', 'Professor')], default='S', max_length=3),
        ),
    ]
