# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20160608_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='user',
            name='study',
        ),
    ]
