# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 08:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 9, 8, 44, 38, 794482, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
